---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: <APP_NAME>
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: <APP_NAME>
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Object
    object:
      describedObject:
        kind: Pod
        name: <CONSUMER_GROUP>
      metric:
        name: consumer-lag
      target:
        averageValue: 1
        type: AverageValue
